#!/bin/bash
# read our configuration
source /boot/config/plugins/controlr/controlr.cfg

vars="/boot/config/plugins/controlr/controlr.env"
prog="/usr/local/emhttp/plugins/controlr/controlr"

# stop it if it's running
killall controlr > /dev/null 2>&1

# run the app
[[ $UPS = "enable" ]] && SHOWUPS="--show-ups" || SHOWUPS=""
# nohup sudo -H bash -c "$prog -port $PORT -certdir '$CERTDIR' $SHOWUPS" > /dev/null 2>&1 &
nohup sudo -H bash -c "env $(cat $vars 2> /dev/null | xargs) $prog --port $PORT" $SHOWUPS > /dev/null 2>&1 &
