#!/bin/bash
# read our configuration
source /boot/config/plugins/controlrd/controlrd.cfg

vars="/boot/config/plugins/controlrd/controlrd.env"
prog="/usr/local/emhttp/plugins/controlrd/controlrd"

# stop it if it's running
killall controlrd >/dev/null 2>&1

# run the app
[[ $UPS = "enable" ]] && SHOWUPS="--show-ups" || SHOWUPS=""
nohup sudo -H bash -c "env $(cat $vars 2>/dev/null | xargs) $prog --port $PORT" $SHOWUPS >/dev/null 2>&1 &
